data:
    dataset: "PNEUMONIA"
    dataset_path: "ddim_pneumonia/datasets/Pneumonia_dataset/chest_xray_preprocessed/train/NORMAL_SUBSET"
    image_size: 256
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: true
    num_workers: 8

model:
    type: "iso"
    in_channels: 1
    out_ch: 1
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16]
    dropout: 0.0
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True
    save_statistics: False

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 5 # x * Num of GPUs
    n_epochs: 1000
    n_iters: 11000
    snapshot_freq: 10000
    # validation_freq: 2000

sampling:
    batch_size: 10
    last_only: True
    n_samples: 500

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
